### ISSUE TITLE
测试自动标签添加 - 第1轮

### ISSUE THREAD

**Issue by Luna-Grace** [fjwxzde/Test#6]

**Comment by Luna-Grace** [comment]
\- https://github.com/fjwxzde/Test/actions/runs/10229595229
```
Run actions/github-script@v7
  with:
    github-token: ***
    script: const issue = context.payload.issue;
  const owner = issue.repository.owner.login;
  const repo = issue.repository.name;
  const issue_number = issue.number;
  const octokit = github.getOctokit(***);
  await octokit.issues.addLabels({
    owner,
    repo,
    issue_number,
    labels: ['DEV-需要注意']
  });
  
    debug: false
    user-agent: actions/github-script
    result-encoding: json
    retries: 0
    retry-exempt-status-codes: 400,401,403,404,4[2](https://github.com/fjwxzde/Test/actions/runs/10229595229/job/28303439193#step:2:2)2
TypeError: Cannot read properties of undefined (reading 'owner')
Error: Unhandled error: TypeError: Cannot read properties of undefined (reading 'owner')
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:[3](https://github.com/fjwxzde/Test/actions/runs/10229595229/job/28303439193#step:2:3)5424:16), <anonymous>:[4](https://github.com/fjwxzde/Test/actions/runs/10229595229/job/28303439193#step:2:4):32)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:3[5](https://github.com/fjwxzde/Test/actions/runs/10229595229/job/28303439193#step:2:5)425:12)
    at main (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35522:2[6](https://github.com/fjwxzde/Test/actions/runs/10229595229/job/28303439193#step:2:6))
    at /home/runner/work/_actions/actions/github-script/v[7](https://github.com/fjwxzde/Test/actions/runs/10229595229/job/28303439193#step:2:7)/dist/index.js:35497:1
    at /home/runner/work/_actions/actions/github-script/v7/dist/index.js:35553:3
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35556:12)
    at Module._compile (node:internal/modules/cjs/loader:135[8](https://github.com/fjwxzde/Test/actions/runs/10229595229/job/28303439193#step:2:8):14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:[10](https://github.com/fjwxzde/Test/actions/runs/10229595229/job/28303439193#step:2:10))
    at Module.load (node:internal/modules/cjs/loader:[12](https://github.com/fjwxzde/Test/actions/runs/10229595229/job/28303439193#step:2:12)08:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
```
